##crash
crash_client: crash_client.c ../lib/readline.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o crash_client crash_client.c ../lib/readline.c  ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
crash_server: crash_server.c ../lib/readline.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o crash_server crash_server.c ../lib/readline.c  ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c