##connect
connect_client: connect_client.c ../lib/readline.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o connect_client  ../lib/readline.c connect_client.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
connect_server: connect_server.c ../lib/readline.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o connect_server connect_server.c  ../lib/readline.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c