####### variable length 
variable_client: variable_client.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o variable_client variable_client.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
variable_server: variable_server.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o variable_server variable_server.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c