####### event 
event_client: event_client.c tselect.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o event_client event_client.c tselect.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
event_server: event_server.c tselect.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c
	gcc -o event_server event_server.c tselect.c ../lib/error.c ../lib/readn.c ../lib/readvrec.c ../lib/set_address.c ../lib/tcp_server.c ../lib/tcp_client.c